---

- name: install apache2
  apt: name=apache2 update_cache=yes state=latest
  become: yes
  become_user: root


#apt: name={{item}} update_cache=yes state=latest: si on veut lancer en boucle
#when: user is defined : pour filtrer des taches


- name: "apache2 listen on port {{ http_port }}"
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen {{ http_port }}" state=present

- name: apache2 virtualhost on port {{ http_port }}
  lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>" state=present backrefs=yes
  notify:
    - restart apache2

#toutes les taches qui dependent de domains seront dans un fichier independant pour les jouer en boucle
- include_tasks: config_hosts.yml
  with_items:
    - "{{ domains }}"   
