---

#sudo ansible-playbook -i"inventory/dev" helloworld.yml --extra-vars "version=1.01.00 other_variable=foo"
#sudo ansible-playbook -i"inventory/dev" purge.yml"
#cat /etc/passwd to see all users
#cat /etc/group to see all groups
- hosts: local
  vars:
    http_port: 8081
    domains:
       - "example.com"
       - "ajconsulting.com"
       - "rte.com"
    totos:
       - toto
       - titi
       - tata
    demo_users:
       usr30:
          pwd: pkis
          grp: demo-ansible
       usr31:
          pwd: pkgf
          grp: demo-ansible
    ftp_directories:
       - { name: 'ftp1', mode: '0770', owner: 'thales' }
       - { name: 'ftp2', mode: '0770', owner: 'thales' }


  roles:
    - user
    - apache
    - file-demo
    - user-demo	


#   - name: stop apache2
#     service: name=apache2 state=stopped

#   - name: restart apache2
#     service: name=apache2 state=started

#   - name: restart apache2
#     service: name=apache2 state=restarted


    
