---
- name: Hello World!
  hosts: container-host
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."

  - name: Create directory /home/thales/demodemo
    file: path=/home/thales/demodemo state=directory recurse=yes owner=thales group=thales mode=0777
